on:
  workflow_dispatch: {}
name: Update dependencies
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install pnpm and dependencies
      uses: pnpm/action-setup@v2.1.0
      with:
        version: 6.11.5
        run_install: |
          args: [--frozen-lockfile]

    - name: package-update
      uses: vsramalwan/actions-package-update@eb5a57c43b045de109df8de4ec80373e37ed1ce1
      env:
        AUTHOR_EMAIL: john@example.com
        AUTHOR_NAME: john
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
        UPDATE_COMMAND: pnpm
      with:
        args: update
